# Start from the Rocker/Shiny base image
FROM rocker/shiny

# Install R packages
RUN apt-get update && apt-get install -y \
    libpq-dev \
    curl \
    libxml2-dev \
    libssl-dev
	
# Install R packages using R's built-in 'install.packages' function.
RUN R -e 'install.packages(c("DBI", "RPostgres", "ggplot2", "tidyverse"))'

# Expose the default Shiny Server port
EXPOSE 3838

# Start Shiny Server
CMD ["/usr/bin/shiny-server"]

